### ISSUE TITLE
Server cannot shutdown on Server.py

### ISSUE THREAD

**Issue by mi-24v** [ptr-yudai/ltkit#1]
`Server.py` の実行中、ServerをStandした後Stopできない現象を確認しました。
スタックトレースは以下の通りです。
![stack trace](https://cloud.githubusercontent.com/assets/7941947/15051246/910da912-1332-11e6-9989-60978d30d297.png)

**Comment by mi-24v** [comment]
## 実行環境
- Windows8.1 64-bit
- Python2.7.8 32-bit

**Comment by ptr-yudai** [comment]
Fixed!
